### ISSUE TITLE
Arrow jumps when there are icons on the search results

### ISSUE THREAD

**Issue by feinstein** [jchafik/google-search-shortcuts#11]
I installed Bitdefender, which scans my Google Results and places an icon in front of the result, the problem is, if the result is long, when I click the result the arrow from this extension appears and makes the link jump to the next like:

![image](https://user-images.githubusercontent.com/8120472/65729543-13e47900-e095-11e9-8fc5-254dc70453c5.png)

It was supposed to be like this:

![image](https://user-images.githubusercontent.com/8120472/65729557-23fc5880-e095-11e9-9669-ad7809110fdd.png)

This is very annoying since my clicks are being dodged, I would appreciate it a lot if you could fix this.

Bitdefender alters the HTML adding the icons, it's not an extension, it scans my network traffic and modifies it.

**Comment by jchafik** [comment]
I'll be removing the arrow style entirely shortly. In the interim, you can uncheck "Prepend arrow" from the options and instead select "Add additional styling to the selected search result".
