### ISSUE TITLE
Is this repo and extension unmaintined?

### ISSUE THREAD

**Issue by OskarNS** [jchafik/google-search-shortcuts#13]
The extension is now somewhat broken and this repo hasn't been updated in years. Is it unmaintained?  :) @jchafik

**Comment by jchafik** [comment]
It is being maintained, but not a priority for feature requests at the moment. What bug(a) did you find? I still use it daily without issue.

**Comment by myfonj** [comment]
Ext works well for me (both in Fx and Chrome); but this repo shows latest commit from "Nov 29, 2018" but [AMO](https://addons.mozilla.org/en-US/firefox/addon/google-search-result-shortcuts/versions/) reads "Latest version 1.1.9 Released Mar 25, 2019", so this repo is maybe missing some push?

([Chrome Store](https://chrome.google.com/webstore/detail/google-search-keyboard-sh/iobmefdldoplhmonnnkchglfdeepnfhd) shows same version with release date Nov 28, 2018.)

**Comment by jchafik** [comment]
I initially missed releasing to Firefox, hence the difference in dates. Both are running the same version, with the latest copy of the repo.
