### ISSUE TITLE
Is the extension broken?

### ISSUE THREAD

**Issue by bb2020** [jchafik/google-search-shortcuts#16]
Hi. Thanks for this awesome extension. Today I realized there is an issue with it. A rectangular box is drawn around the first result and pressing `tab` does nothing.

Chrome Linux 85.0.4183.121 (Official Build) (64-bit)
Extension 1.1.10

![image](https://user-images.githubusercontent.com/19290397/94802174-d9bc5e80-03ef-11eb-8bae-91796f66a97d.png)

**Comment by prxtiksingh** [comment]
Hi. I'm facing the same issue in chrome Version 85.0.4183.121 (Official Build) (64-bit) as well as firefox 81.0

**Comment by kennethkth** [comment]
Hi Jacob. I'm facing the same issue on the latest version of chrome for Windows. Hopefully you can fix this issue soon. Thank you for this wonderful extension.

**Comment by jchafik** [comment]
Thanks. A recent Google update did break the extension. A fix has been submitted to the Chrome store and should auto update once it passes review.

**Comment by MatthiasKunnen** [comment]
@jchafik, is a Firefox update pending approval too?

**Comment by jchafik** [comment]
@MatthiasKunnen The Firefox version should be available. Please let me know if it's not for you.
