### ISSUE TITLE
Feature request: Extend support for youtube

### ISSUE THREAD

**Issue by kennethkth** [jchafik/google-search-shortcuts#17]
Hi @jchafik. Thank you for this awesome extension. I was wondering if it is possible for you to add support for tab based navigation for youtube.com as well?

**Comment by jchafik** [comment]
Sorry, I have limited time to work on the extension and will be prioritizing the stability of the Google search results. If you would like to submit a PR with functionality for YouTube, I would be happy to review and merge.
