### ISSUE TITLE
Bug report: Recent update to Google breaks keyboard shortcuts

### ISSUE THREAD

**Issue by jat255** [jchafik/google-search-shortcuts#19]
Noticed this today that if I use `Tab` or the `Down` arrow after a search, it's jumping immediately to the second "O" in the google page controls at the bottom of the page, so it looks like they must have changed their markup in a way that's not compatible with the extension.

Example image:
![image](https://user-images.githubusercontent.com/1278301/98411140-c3c73c80-2032-11eb-8050-b8f145f35094.png)

**Comment by jchafik** [comment]
Thank you for the report. I was finally able to get Google to render the updated version on my machine. I've submitted a patch to Google and it should be available shortly.

**Comment by tuan-lm** [comment]
Look like this bug is still exist. The extension just auto focus on the pagination at the bottom of the google search page

**Comment by MatthiasKunnen** [comment]
@tuan-lm, I believe Google updated some classes so the selectors need an update

**Comment by tuan-lm** [comment]
The bug seem to be fix recently. Great job to the author
