### ISSUE TITLE
Focus and select search box text on ESC

### ISSUE THREAD

**Issue by poeik** [jchafik/google-search-shortcuts#2]
Could you please grant my account permissions to create a new branch and push to it? I added a function to select the text in the searchbox on hitting esc-key. If you allow, I'd love to make a pull-request on master. So you can review my code (only few lines) and merge if you want. 
Thank you

**Comment by jchafik** [comment]
Feel free to fork the repo (you should be able to fork and then submit a PR). I wouldn't mind reviewing your code if you'd like, but I probably wouldn't merge it since the standard function of the ESC key is to blur objects, not focus/select them.

**Comment by poeik** [comment]
Yes you're right. Actualy it's not the standard function of ESC. But it was a feature before Google removed the instant search feature. When you pressed ESC, the focus went to the searchbar and highlighted the text in the searchbar (like when you press ctrl+a in the searchbar). 
So I just thought some users (for example me) would like that feature. When you look in chrome webstore, there is already one user requesting for that feature. Maybe we could map that functionality to another key? What do you mean?

**Comment by jchafik** [comment]
Good points. Go ahead and submit a PR, I'll merge it
