### ISSUE TITLE
Google search page adds an extra space

### ISSUE THREAD

**Issue by ducalpha** [jchafik/google-search-shortcuts#21]
I enabled "Focus to search box on any key" which is super convenient. However, my Google search page now displays `Press "/" to jump to the search box` and a space is insert to the query every time I type.
Expected result: no space added when typing.
Actual result: an extract space added and `Press "/" to jump to the search box` pops up.

**Comment by jchafik** [comment]
Google actually added the ability to press "/" to jump to the search box. I'll remove that portion of functionality from the extension entirely.

**Comment by jchafik** [comment]
This has been fixed with the change pushed to the Chrome store.
