### ISSUE TITLE
Doesn't select main search results anymore

### ISSUE THREAD

**Issue by CodeCreator** [jchafik/google-search-shortcuts#23]
I think google switched the order of the `<h3>` and `<a>` tags on the search results page, so changing the query selector form `document.querySelectorAll('h3 a, ...")` to `document.querySelectorAll('a h3, ..."),` as well as the equivalent for the focused selector `document.querySelector('h3 a:focus, ...")` should do the trick. This is at least the case for me currently, maybe Google is doing a slow rollout.
Thanks for the extension btw!

**Comment by jchafik** [comment]
Fix pushed and should be available shortly. Thanks for the report!

**Comment by Newgap** [comment]
Is a new version coming to Firefox?

**Comment by myfonj** [comment]
Just got the update in Firefox.

Thanks for keeping this up!
