### ISSUE TITLE
Google updated the search result page

### ISSUE THREAD

**Issue by MatthiasKunnen** [jchafik/google-search-shortcuts#24]
- New selector required for main search results (fixed by #22)
- Related search results seem to be only images now  (fixed by #22)
- They seem to be experimenting with a focus search option so some of this extension's code might no longer be needed
  ![image](https://user-images.githubusercontent.com/16807587/114787862-ba2fc680-9d80-11eb-9d7e-a4078a0aac14.png)

**Comment by kennethkth** [comment]
Hello Mr. Mathhias,
Is the bug fixed now? Any ETA on how many days it will take for the extension to be updated on chrome store?

**Comment by MatthiasKunnen** [comment]
@kennethkth, unfortunately, raising an issue and PR is the only thing I can do. The owner, @jchafik, will need to either merge my PR, or make the necessary changes themselves, followed by updating the extension.

**Comment by kennethkth** [comment]
Thanks Matthias. Hopefully, it gets updated soon. This extension is a life-saver @jchafik

**Comment by bb2020** [comment]
We all meet again when the search is broken.

**Comment by pasquale95** [comment]
Same error here. Does anyone have found a quick solution? I see this error in my js console when I click on an arrow key.
![image](https://user-images.githubusercontent.com/26608445/114897398-7b961c80-9e11-11eb-9545-43af4e23a332.png)

**Comment by pasquale95** [comment]
Just tried the update by @MatthiasKunnen. It works like a charm! I'm going to use this version in the meanwhile it is merged and released on the chrome web store.
Thanks!

**Comment by jchafik** [comment]
Version has been updated with some edits/bug fixes and submitted to the Chrome and Firefox web stores. It should be live in the next hour or so. Thanks @MatthiasKunnen for the contributions!
