### ISSUE TITLE
Input not focused when typing a key with modifier

### ISSUE THREAD

**Issue by AltarBeastiful** [jchafik/google-search-shortcuts#30]
I'm using a AZERTY keyboard and numbers are only accessible with Shift modifier. 
As the extension filters out all keys with modifiers, I cannot focus input using directly numbers.

Why does the extension not focus input on keys with modifiers in the first place ?
And could it be disabled, adapted to allow certain modifiers like Shift?

**Comment by jchafik** [comment]
Modifiers are ignored so the extension does not unintentionally hijack default browser behavior. For example, `CMD+Down Arrow` should bring the user to the bottom of the page. `Shift+Space` would bring the user up the page.

I'd recommend selecting `Vim Style` under the extension options. That way, you can focus the search input using a slash (`/`).

Hope that helps!
