### ISSUE TITLE
The selectors only select related searches in Firefox

### ISSUE THREAD

**Issue by MahdiNazemi** [jchafik/google-search-shortcuts#32]
I use this extension regularly and have found it extremely useful in Chromium-based browsers.
Today, I wanted to use the extension in Firefox after a long time and found out the selectors only select related searches instead of search results. After looking at the most recent reviews on the Firefox Addons page, I found that a few other people have reported the same issue.

I am a bit puzzled about why the selectors work in one browser but not the other. Can you please look into the Firefox version and see if anything differs from the Chrome version?

Thanks!

**Comment by buschtoens** [comment]
I already looked into this in the past: #29

**Comment by MahdiNazemi** [comment]
Thanks for the comment. I'll close the issue as duplicate then.

@buschtoens Do you know if the repo's owner is still maintaining it?

**Comment by jchafik** [comment]
Hey @MahdiNazemi - I just wanted to let you know that I've merged @buschtoens's PR and a new version has been submitted to Chrome and Firefox.
