### ISSUE TITLE
inputElementIds Array initialized with incorrect id value for google calculator widget

### ISSUE THREAD

**Issue by marti2221** [jchafik/google-search-shortcuts#33]
I have tried search the 'cwtltblr' value initialized in the inputElementIds Array via chrome dev tools but cannot find the value anywhere. Has the calculator widget been updated with a new Id?

**Comment by jchafik** [comment]
The calculator widget no longer uses an input element, which makes it unnecessary. However, I'll keep the block for backward compatibility (never know when Google may rollback their change / who it's rolled out to).
