### ISSUE TITLE
Left / right arrow should go to search box

### ISSUE THREAD

**Issue by dzid26** [jchafik/google-search-shortcuts#34]
If I want to add a word in the middle of the search, I  need to write a dummy character, backspace it, and then move the cursor to where I wanted. 
A better way would be to jump to the search box on left/right arrow stroke. 

The left arrow should put the cursor to the right, the right arrow should put the cursor to the left.

**Comment by jchafik** [comment]
There is an option you can toggle to disable adding the additional space. See "Add a space when focusing the search box".

While I appreciate what you're trying to do, I don't think using arrow keys to focus the search box is intuitive enough to justify merging. You're welcome to build the extension locally with your changes (from this and the other PR).

**Comment by dzid26** [comment]
Sure.  
I use the left arrow all the time, now that I added this function. Comes naturally to me. 
Thanks for the good extension.
