### ISSUE TITLE
Automatic focus in the Google searchbar not working anymore when typing 

### ISSUE THREAD

**Issue by pasquale95** [jchafik/google-search-shortcuts#36]
Hi,
since today I experience the following problem. Here the steps:
- I type something in the Chrome search bar, which automatically performs the search with Google;
- Once the result page is available, I start typing to add more words in the Google search bar (not the Chrome one). Before as soon as I started typing the focus moved immediately inside the search bar allowing me to write there. Now this doesn't happen anymore.

Does anyone else experience the same issue?

Below some screenshots of the error:

<img width="1001" alt="Screenshot 2023-04-13 at 09 37 25" src="https://user-images.githubusercontent.com/26608445/231688157-cae04cb5-f56d-45e7-bc27-5dd2b770e1fc.png">

<img width="539" alt="Screenshot 2023-04-13 at 09 37 33" src="https://user-images.githubusercontent.com/26608445/231688164-725dc879-18d5-4dbb-9e3c-4f4fa067ef4c.png">

**Comment by pasquale95** [comment]
Hi @jchafik, did you get a chance to look into such issue? I guess it's an issue that more people are experiencing...

**Comment by pasmai** [comment]
This should fix it: https://github.com/jchafik/google-search-shortcuts/pull/37
@jchafik Please have a look at it and update the extension if you approve the change.

**Comment by pasmai** [comment]
If you want to continue using the search box extension with the fix:
https://github.com/pasmai/google-search-shortcuts/

* Download the fixed version
* Unpack the .zip somewhere
* Then go to Manage Extensions
* Select the unpacked folder

<br>

<img src="https://user-images.githubusercontent.com/14838120/233593638-0db8fab9-68cb-47b2-a06e-ebb1ea2cd896.png" width=80%>
<br>

---

<br>
<img src="https://user-images.githubusercontent.com/14838120/233593967-1cef16e5-c929-44a5-acba-c6a9c20a1e50.png" width=80%>

**Comment by pasquale95** [comment]
Great! Thanks!

**Comment by jchafik** [comment]
Hey all, an update has been pushed to the Chrome store with the fix and should be live shortly (hopefully today)
