### ISSUE TITLE
Arrow Selector Not Shown

### ISSUE THREAD

**Issue by joshg111** [jchafik/google-search-shortcuts#6]
Down arrow or tab use to show an arrow selector next to a search result, but now it doesn't. I'm able to work around this by turning on the `add additional styling` option, but the arrow still doesn't show. 

I'm on mac os.

**Comment by StefanHumberg** [comment]
Same for me on Windows with Chrome 69.0.3497.100 (Offizieller Build) (64-Bit) and Google Search Keyboard Shortcuts 1.1.7. After activation of add additional styling option in advanced settings i now have a blue bar next to the results. 

This of course means i can work with that, you should decide if that's what you are trying to achieve and maybe simply set this as a default or do something else about it...

Regards,
Stefan

**Comment by jchafik** [comment]
Google recently updated their search results page. I've updated the stylesheet for the arrow selector to account for those changes. I'll push an update shortly. Thanks for the heads up!
