### ISSUE TITLE
Firefox version steps to Google "Os" instead of search results

### ISSUE THREAD

**Issue by philmaweb** [jchafik/google-search-shortcuts#7]
Recently one of my favorite addons stopped working - Google Search Result Shortcuts!

Instead of stepping through the search results, it steps through the Google Os.
It's still working for DuckDuckGo search results.

See screencast at  https://vimeo.com/293009465
.

Using the 1.1.6 version in the firefox store (newest available here).

Would it be possible to publish the newest 1.1.7 changes to the firefox store too?

**Comment by jchafik** [comment]
I'll push an update to FireFox shortly. Please let me know if you continue to have any issues on 1.1.8.
